stages:
  - build

variables:
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version
  MAVEN_REPO_LOCAL: .m2/repository

build:
  stage: build
  image: liberica-openjdk-centos:8u292
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - $MAVEN_REPO_LOCAL
      - wc/node
      - wc/node_modules
  script:
    - ./mvnw -Dmaven.repo.local=$MAVEN_REPO_LOCAL $MAVEN_CLI_OPTS package
